##############################################################                              
#                          xCommands                         #
#                        Version: 0.01                       #
#				              Authors: Devo & Devi                   #       
##############################################################

########################
# Join & Quit Settings #
########################
enable-massage: true
join-massage: ' '
quit-massage: ' '